### ISSUE TITLE
A way to specify the config/ sources and target paths

### ISSUE THREAD

**Issue by andrewmoko** [velo/maven-formatter-plugin#12]
Hey

I am integrating this plugin into an existing maven project. I am required to place the java/javascript formatter xml under ../src/config/eclipse/formatter. The plugin looks for the sources in the wrong directory, and the compiled target/classes are equally misplaced.

Is there a way to pass the directory paths (maybe via command line)?

Thanks

-Andrew

**Comment by velo** [comment]
What do you mean by "plugin looks for the sources in the wrong directory"?

**Comment by andrewmoko** [comment]
I could be wrong but, am I required to place the js formatter in a specific directory (say ../src/config/eclipse/formatter)? If yes, is there a way to use a customized directory structure? 

Our source code (sources) is in a slightly different directory structure as well (omod/src/main/java/...). Is this configurable?

If I am not clear kindly let me know and I'll explain further with examples. 

Thanks

-Andrew

**Comment by velo** [comment]
Like this?
https://github.com/mpollmeier/orientdb-gremlin/blob/master/driver/pom.xml#L184

**Comment by andrewmoko** [comment]
Just what I was looking for. Thanks a bunch

**Comment by velo** [comment]
Cool
