### ISSUE TITLE
_ in numeric literals causes entire method to be misformatted

### ISSUE THREAD

**Issue by Legioth** [velo/maven-formatter-plugin#20]
`_` in a numeric literal, e.g. `int thousand = 1_000;` that was introduced in Java 7 causes the formatter to use something that appears to be default settings for the entire method, producing formatting without any spaces or line breaks. This is not consistent with how the same method is formatted by Eclipse Neon.2.

If it matters, the configuration file I've been testing with is https://github.com/vaadin/framework/blob/8491ea68d32a275bb70998db5f66759265d367b8/eclipse/VaadinJavaConventions.xml

One example of a file that becomes misformatted is https://github.com/vaadin/framework/blob/cd73480c602326c4bbb2872e0839d14626199551/server/src/test/java/com/vaadin/data/validator/BeanValidatorTest.java where the body of the method `testAddressNestedPropertyInvalidPostalCodeFails` is formatted as
```
assertFails(100_000,"must be less than or equal to 99999",validator("address.postalCode"));
```

whereas the formatting produced through Eclipse are
```
assertFails(100_000, "must be less than or equal to 99999",
        validator("address.postalCode"));
```

Tested using version 1.8.1 of the plugin.

**Comment by velo** [comment]
Are you certain that the same configuration is being used on Eclipse AND on the plugin (must ask)

Keep in mind that 1.8.1 is using Neon SR1 as engine, make sure to use the exact same.

**Comment by Legioth** [comment]
> Are you certain that the same configuration is being used on Eclipse AND on the plugin (must ask)

Yes. Eclipse and the plugin are formatting most files in exactly the same way. The only differences I've encountered is this one as well as another similar edge case that I'll report separately once I've isolated the exact situation for when it happens (provided it's not just a difference between SR1 and SR2).

> Keep in mind that 1.8.1 is using Neon SR1 as engine, make sure to use the exact same.

I manually verified that SR1 gives exactly the same formatting as my regular SR2 for the affected file.

**Comment by velo** [comment]
Can you help me on reproducing the issue?

#22

**Comment by velo** [comment]
If you could include the required option to reproduce the problem...
https://github.com/velo/maven-formatter-plugin/pull/22/files#diff-2844c1574936a15b1f30d77f17e959ecR38

**Comment by Legioth** [comment]
I think I nailed down another significant part of the puzzle. I haven't had time to investigate it thoroughly, but it might give you some quite good clues about what to look for.

It turns out that our formatting settings file is exported from whatever Eclipse version we were using in the beginning of 2014. Importing it into Neon and exporting again makes the file grow by about 40 lines. 

This issue is no longer observed when running the plugin with the re-exported settings file.

My guess without looking at any code from Eclipse or the plugin is that different default values are used for settings that are not present in the setting file, and then that difference causes the formatter to completely fail when dealing with a method where it needs to consult some specific setting value.

I could go through the differences between our original settings file and the newly exported one to find out which setting it is that causes this issue, but I might unfortunately not have time to do that right now.

**Comment by velo** [comment]
Eclipse probably included new settings that defaults to different values
while importing.

Glad the issue is done, won't do anything then.

**Comment by Legioth** [comment]
I tracked down the offending settings and created #24 about dealing with that more general mismatch.
