### ISSUE TITLE
Is the work on this repo being contributed back to https://github.com/revelc/formatter-maven-plugin ?

### ISSUE THREAD

**Issue by mitermayer** [velo/maven-formatter-plugin#28]
I was wondering if the work on this fork will endup on https://github.com/revelc/formatter-maven-plugin ?

**Comment by velo** [comment]
Fair question...  

Yes https://github.com/revelc/formatter-maven-plugin/compare/master...velo:master?expand=1, but need someone to fix the conflicts

**Comment by velo** [comment]
Keep in mind, this project is not a fork per say.

This project originated from the original inactive code google project.

Once, I made the effort required to "merge" my version back to revelc.... and since then no releases were made at revelec.

So I decide to keep developing this one.

**Comment by velo** [comment]
Also, there is this question about using bleeding edge eclipse versions or enterprise stable versions...
https://github.com/revelc/formatter-maven-plugin/issues/154

I will keep pushing for bleeding edge, which allows this version to have JAVA9 support on the latest release.

**Comment by velo** [comment]
I guess in the end my answer shouldn't be yes.... it's more it could...  but at this point I don't have any plans on doing the manual merge again
