### ISSUE TITLE
Plugin doesn't format javadocs

### ISSUE THREAD

**Issue by zloygreko** [velo/maven-formatter-plugin#42]
It seems plugin does not format javadocs.
Looks that the issue was inherited from revelc/formatter-maven-plugin (from which this one is forked).
They fixed it by updating the argument passed to the formatter from CodeFormatter.K_COMPILATION_UNIT
to 
CodeFormatter.K_COMPILATION_UNIT | CodeFormatter.F_INCLUDE_COMMENTS.
(refer to this issue https://github.com/revelc/formatter-maven-plugin/issues/192)

Is it possible to make the same fix in this plugin?

**Comment by velo** [comment]
Sure, changes on master, release will happen shortly

**Comment by velo** [comment]
@rultor release, tag=`2.2.0`

**Comment by zloygreko** [comment]
Thanks!
